language: python

python:
  - 2.7

services:
    - redis-server
    - mysql

install: pip install -r requirements.txt pytest-cov python-coveralls

before_script:
  - mysql -e "CREATE DATABASE pypi_portal_testing;"
  - 'echo -e "_SQLALCHEMY_DATABASE_USERNAME: travis\n_SQLALCHEMY_DATABASE_PASSWORD: \"\"" > config.yml'

script: make test

after_success: coveralls -i
